services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8010:2368
    environment:
      database__client: mysql
      database__connection__host: $DB_HOST
      database__connection__user: $DB_USER  
      database__connection__password: $DB_PASSWORD
      database__connection__database: $DB_NAME
    volumes:
      - ghost:/etc/w2l/ghost/content

volumes:
  ghost: